### PR TITLE
fix: check if the snapshot version contains a commit

### LINKED ISSUE #1405: Check if the beat version snapshot contains a git commit
I think we need to improve the automated bump with removing the calculation of the BeatVersionBase, which comes including the hash:

```golang
v, err := utils.GetElasticArtifactVersion(BeatVersionBase)
if err != nil {
	log.WithFields(log.Fields{
		"error":   err,
		"version": BeatVersionBase,
	}).Fatal("Failed to get Beat base version, aborting")
}
BeatVersionBase = v
```
A possible change could be to carry the fallback version between checks, replacing the `log.Fatal` with `log.Warn`:
```golang
v, err := utils.GetElasticArtifactVersion(BeatVersionBase)
if err != nil {
	log.WithFields(log.Fields{
		"error":   err,
		"version": BeatVersionBase,
	}).Warn("Failed to get Beat base version, aborting")
} else {
	BeatVersionBase = v
}
```

@adam-stokes wdyt?

_Originally posted by @mdelapenya in https://github.com/elastic/e2e-testing/issues/1391#issuecomment-888032893_

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
When checking the version using Elastic's versions API, this PR adds a verification for the version to have a commit sha between the semver version and the SNAPSHOT suffix. If it does contain it, then the API is not looked up. To achieve it we added a helper method as an utility, where we use a regex that checks for `X.Y.Z-sha-SNAPSHOT`. We added unit tests verifying the new behaviour.

On the same hand, we noticed that the existing `IsCommit` method would return true for this hashed snapshots, so when checking Kibana version we used that method to change the Docker namespace for the image. With the previous implementation the method would return true, changing the namespace to `observability-ci`. For that reason we improved the regex in there to check for commits from the first position in the checked string.

## Why is it important?
The automation to bump the versions replaces the current version with i.e. `8.0.0-abcdef-SNAPSHOT`. That version was used to look up the versions API, and because it does not exist, the tests fails with a log.Fatal: because the stack (ES, Kibana, Fleet-Server) is considered a runtime dependency, we cannot run the tests without it. With this change, we simply use the version as it is, without the versions API (which is used to resolve version aliases).

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ] regex masters, can you review the new regex? :pray:

## How to test this PR locally

```shell
# run unit tests
$ make unit-test

# run e2e tests with a hashed version
$ TAGS="apm_server" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE BEAT_VERSION="8.0.0-ae1e1c3b-SNAPSHOT" DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e/_suites/fleet functional-test

# run e2e tests with a fixed version without commit
$ TAGS="apm_server" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE BEAT_VERSION="8.0.0-SNAPSHOT" STACK_VERSION=8.0.0-SNAPSHOT DEVELOPER_MODE=true ELASTIC_APM_ACTIVE=false make -C e2e/_suites/fleet functional-test
```

## Related issues

- Closes #1405
- Unblocks any automated bump PR: #1391 #1403

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

File: internal/utils/utils.go [hunk 1]
```diff
@@ -589,7 +594,7 @@ func getBucketSearchNextPageParam(jsonParsed *gabs.Container) string {
 
 // IsCommit returns true if the string matches commit format
 func IsCommit(s string) bool {
-	re := regexp.MustCompile(`\b[0-9a-f]{5,40}\b`)
+	re := regexp.MustCompile(`^\b[0-9a-f]{5,40}\b`)
```
Comment (mdelapenya) [inline internal/utils/utils.go:597]: Before this change, it captured the sha in whatever position of the string, so `8.0.0-abcdef-SNAPSHOT` was matched. Therefore this block: https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/fleet/ingest_manager_test.go#L153-L157, was incorrectly evaluated to true.

**Review by cachedout — APPROVED** [review]
