### PR TITLE
fix: use PRs configuration files

### LINKED ISSUE #953: Download Beats files from the commit, not from the branch
We are always downloading descriptors from the maintenance branch, but for Beats PR we should use the files.

As a consequence, when using local Beats repo, we should honour the path to the file.

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It uses a PR's configuration files in those test suites that requires downloading them from Github (or reading them from a well-known location). We are refactoring the logic to make it reusable.

In the process, we detected that the Docker namespace was not changed for local mode.

## Why is it important?
It will consume the artifacts produced by a PR, not those in the target branch (master, 7.x, etc).

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## How to test this PR locally

**Testing from local workspace**
It requires the metricbeat images to be already built in the local Beats repo.
```shell
SUITE="metricbeat" TAGS="metricbeat" DEVELOPER_MODE="true" BEATS_LOCAL_PATH="/Users/mdelapenya/.op/git/beats" TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE make -C e2e functional-test
```

**Testing a Pull request**
```shell
SUITE="metricbeat" TAGS="metricbeat" GITHUB_CHECK_SHA1="335911c7ab05b9d38bb426652f20215f2bcec164" BEATS_USE_CI_SNAPSHOTS=true TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```

## Related issues

- Fixes #953

## Follow-up
Very probably mergify won't be able to backport this, as the PR is changing a line where the target branch (master, 7.x, etc) is changed. Let's use `backport` tool resolving conflicts locally instead.

### CODE REVIEW

**Comment by adam-stokes** [comment]
I did file this today but I think your approach is better https://github.com/elastic/e2e-testing/issues/955

**Review by adam-stokes — APPROVED** [review]

File: e2e/_suites/fleet/stand-alone.go [hunk 1]
```diff
@@ -47,10 +47,18 @@ func (sats *StandAloneTestSuite) afterScenario() {
 	}
 
 	if _, err := os.Stat(sats.AgentConfigFilePath); err == nil {
-		os.Remove(sats.AgentConfigFilePath)
-		log.WithFields(log.Fields{
-			"path": sats.AgentConfigFilePath,
-		}).Debug("Elastic Agent configuration file removed.")
+		beatsLocalPath := shell.GetEnv("BEATS_LOCAL_PATH", "")
+		if beatsLocalPath == "" {
+			os.Remove(sats.AgentConfigFilePath)
```
Comment (mdelapenya) [inline e2e/_suites/fleet/stand-alone.go:52]: Do not remove files from the local repository

File: e2e/_suites/metricbeat/metricbeat_test.go [hunk 2]
```diff
@@ -363,18 +371,11 @@ func (mts *MetricbeatTestSuite) installedUsingConfiguration(configuration string
 
 	metricbeatVersion = e2e.CheckPRVersion(metricbeatVersion, metricbeatVersionBase)
 
-	// use master branch for snapshots
-	tag := "v" + metricbeatVersion
```
Comment (mdelapenya) [inline e2e/_suites/metricbeat/metricbeat_test.go:367]: I think this is not needed anymore, as we will never build an URL for a tag, always branches or commits.

File: e2e/steps/configurations.go [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+	"github.com/elastic/e2e-testing/cli/shell"
+	"github.com/elastic/e2e-testing/e2e"
+	log "github.com/sirupsen/logrus"
+)
+
+// FetchBeatConfiguration where 'configFileName' represents the configuration file, including extension.
+// It will read environment to determine if it must read a file from the local file system, or in the
+// contrary, download a file from Github. In the latter case, it will use a commit of the maintenance branch
+// used in the tests
+func FetchBeatConfiguration(xpack bool, beat string, configFileName string) (string, error) {
```
Comment (mdelapenya) [inline e2e/steps/configurations.go:19]: We should probably extract code for configurations management to here, instead of the huge utils.go file :/

File: e2e/_suites/metricbeat/metricbeat_test.go (hunk 2 above)
Comment (adam-stokes) [reply e2e/_suites/metricbeat/metricbeat_test.go:367]: Would that still be the case we if stick to testing the way the front facing user documentation suggests?

File: e2e/_suites/fleet/stand-alone.go (hunk 1 above)
Comment (adam-stokes) [reply e2e/_suites/fleet/stand-alone.go:52]: I made a comment in #955, perhaps we should think about keeping `~/.op/compose` fully controlled by us and allow developers to utilize like a `~/.op/compose.d` for anything custom?

File: e2e/_suites/metricbeat/metricbeat_test.go (hunk 2 above)
Comment (mdelapenya) [reply e2e/_suites/metricbeat/metricbeat_test.go:367]: Did I forget updating a link? 🤦‍♀️  Please let me know it and will update the PR tomorrow
