### PR TITLE
fix: use beat_version as fallback if it's provided

### LINKED ISSUE #1197: [7.13.x] Beats branches are failing
See https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.13.x/39/pipeline

## Steps to reproduce:
```shell
export BEATS_USE_CI_SNAPSHOTS=true
# git sha1 from the above build:
export GITHUB_CHECK_SHA1=b332fc28794083e360eac220a5150b443dec6d15
SUITE="fleet" TAGS="stand_alone_agent" TIMEOUT_FACTOR=3  LOG_LEVEL=TRACE  DEVELOPER_MODE=true \
    make -C e2e functional-test
```

## Possible root cause
The artifact is resolved as 7.13.0-SNAPSHOT, when the bucket contains an artifact for 7.13.1-SNAPSHOT. See [bucket on GCP](https://console.cloud.google.com/storage/browser/beats-ci-artifacts/commits/b332fc28794083e360eac220a5150b443dec6d15/elastic-agent?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22,%22s%22:%5B(%22i%22:%22objectListDisplayFields%2Ftype%22,%22s%22:%221%22),(%22i%22:%22displayName%22,%22s%22:%220%22)%5D))&project=elastic-observability&prefix=&forceOnObjectsSortingFiltering=false)

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It uses the BEAT_VERSION variable as fallback when provided. For that reason, upstream jobs must provide the Beat version, as they must know in which version they want to run the tests.

On the same hand, we are simplifying the methods to calculate the paths, removing the need to pass a fallback version, as this is already calculated at the initialisation of the configuration/environment, within the InitVersions method.

## Why is it important?
Builds triggered by Beats maintenance branches are not able to calculate the right paths to fetch binaries from GCP, and this is caused because the Beats version is a moving target that cannot be calculated without inspecting Beats code (libbeat/version/version.go). I.e., last 7.13 commit is using 7.13.2 as version, which created 7.13.2-SNAPSHOT artifacts in GCP.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## How to test this PR locally

```shell
git checkout 7.13.x
TAGS="fleet_mode_agent && install" GITHUB_CHECK_SHA1=ad5f805dd30118cba3748189ef03bb945c958628 TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE BEATS_USE_CI_SNAPSHOTS=true DEVELOPER_MODE=true BEAT_VERSION=7.13.2-SNAPSHOT make -C e2e/_suites/fleet functional-test
```

## Related issues

- Closes #1197

## Follow-ups
We need to pass the BEAT_VERSION in the Beats' packaging job, reading from `make get-version' appending `-SNAPSHOT`. Will send a PR ASAP

### CODE REVIEW

File: e2e/_suites/kubernetes-autodiscover/autodiscover_test.go [hunk 1]
```diff
@@ -135,10 +135,8 @@ func (m *podsManager) configureDockerImage(podName string) error {
 	if useCISnapshots || beatsLocalPath != "" {
 		log.Debugf("Configuring Docker image for %s", podName)
 
-		// this method will detect if the GITHUB_CHECK_SHA1 variable is set
-		artifactName := utils.BuildArtifactName(podName, common.BeatVersion, common.BeatVersionBase, "linux", "amd64", "tar.gz", true)
-
-		imagePath, err := utils.FetchBeatsBinary(m.ctx, artifactName, podName, common.BeatVersion, common.BeatVersionBase, utils.TimeoutFactor, true)
+		artifactName := utils.BuildArtifactName(podName, common.BeatVersion, "linux", "amd64", "tar.gz", true)
+		imagePath, err := utils.FetchBeatsBinary(m.ctx, artifactName, podName, common.BeatVersion, utils.TimeoutFactor, true)
```
Comment (mdelapenya) [inline e2e/_suites/kubernetes-autodiscover/autodiscover_test.go:139]: These two lines are candidates to merge into one method, as they are always called all together

**Review by cachedout — APPROVED** [review]
🥇 💯 Nice!

**Review by adam-stokes — APPROVED** [review]
