### PR TITLE
cli: enable loading default profiles turnkey

### LINKED ISSUE #933: cli: unable to run basic fleet profile
```
⏚ [adam:~/Projects/e2e-testing/cli] master(+27/-1) 3s ± go run main.go run profile fleet
The kibanaConfigPath variable is not set. Defaulting to a blank string.
Creating network "fleet_default" with the default driver
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from elasticsearch/elasticsearch
Digest: sha256:a4a1c524ffea6b3718cb261f5f33373028f7c5687f05cca9172f76be15bdad9c
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
Pulling package-registry (docker.elastic.co/package-registry/distribution:staging)...
staging: Pulling from package-registry/distribution
Digest: sha256:0b7ed7621e14a0803f867fa976f3a973eb140bd9f250ce4f411a9066540da848
Status: Downloaded newer image for docker.elastic.co/package-registry/distribution:staging
Pulling kibana (docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT)...
8.0.0-SNAPSHOT: Pulling from kibana/kibana
Digest: sha256:8c8493885c048551b0813b892ac988651c5c36009773651eb544edfb6a0fb908
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
Creating fleet_package-registry_1 ...
Creating fleet_elasticsearch_1    ...
Creating fleet_package-registry_1 ... done
Creating fleet_elasticsearch_1    ... done
Creating fleet_kibana_1           ...
Creating fleet_kibana_1           ... error

ERROR: for fleet_kibana_1  Cannot create container for service kibana: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for kibana  Cannot create container for service kibana: create .: volume name is too short, names should be at least two alphanumeric characters
Encountered errors while bringing up the project.
ERRO[0103] Could not run the profile.                    profile=fleet
```

### PR DESCRIPTION
**Pull request by adam-stokes**
Fixes #933

Signed-off-by: Adam Stokes <51892+adam-stokes@users.noreply.github.com>

## What does this PR do?

This does a little bit of refactoring of how the profiles are loaded and used. Previously, the packed files were only concerned with locating and accessing a `docker-compose.yml` in the profiles and services. This change allows us to put additional files within the packed binary that may be useful for running profiles and services from the cli. This also forces the cli to utilize the profiles/services after they've been written to disk in the workspace `~/.op`. The files that are packed by default will always be overwritten meaning any changes to our current set of profiles/services will be the latest within the `~/.op` workspace. Custom profiles/services can still be defined by either making a copy of one of the pre-existing profiles/services or creating entirely new directories containing a `docker-compose.yml` file.

## Why is it important?

In order to have the cli experience mirror what happens in CI it is nice to be able to run the commands just as they would be run in CI, but locally. This change allows us to have the same deployments locally that would be done in CI giving us a more unified experience when writing our BDD tests.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [x] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## How to test this PR locally

To get fleet deployed:
```
cd cli
GO111MODULE=on OP_LOG_LEVEL=TRACE go run main.go run profile fleet
```

## Related issues

- Closes #933

### CODE REVIEW

File: cli/config/config.go [hunk 1]
```diff
@@ -296,53 +279,66 @@ func newConfig(workspace string) {
...
+//      configurations/
+//      docker-compose.yml
+//  services/
+//    apache/
+//      configurations/
+//      docker-compose.yml
+//
+// configurations/ directory is optional and only needed if docker-compose.yml needs to reference
+// any filelike object within its parent directory
+func packFiles(op *OpConfig) *packr.Box {
```
Comment (adam-stokes) [inline cli/config/config.go:340]: I mainly left this in here so we could comment on what we're actually packing in the binary

File: cli/config/compose/profiles/fleet/docker-compose.yml [hunk 2]
```diff
@@ -33,7 +33,7 @@ services:
     ports:
       - "5601:5601"
     volumes:
-      - ${kibanaConfigPath}:/usr/share/kibana/config/kibana.yml
+      - ./configurations/kibana.config.yml:/usr/share/kibana/config/kibana.yml
```
Comment (kuisathaverat) [inline cli/config/compose/profiles/fleet/docker-compose.yml:36]: Do we lose any functionality hardcoding the PATH?

Comment (mdelapenya) [reply cli/config/compose/profiles/fleet/docker-compose.yml:36]: I'd say no, as there are keys reading env vars, so it's very coupled to the fleet profile

File: cli/config/config.go [hunk 3]
```diff
@@ -91,12 +91,6 @@ func GetComposeFile(isProfile bool, composeName string) (string, error) {
 		return composeFilePath, nil
 	}
 
-	log.WithFields(log.Fields{
```
Comment (mdelapenya) [inline cli/config/config.go:93]: Are we sure we want to remove this trace log? I sent a PR #946 precisely adding them back when extracting the packed compose directory.

Comment (adam-stokes) [reply cli/config/config.go:93]: This log doesn't really make sense anymore because everything that would've been extracted would have happened already.

Comment (adam-stokes) [reply cli/config/config.go:93]: We could rework the log to not say extracting anymore? That way we can trace if it finds a docker-compose or not. wdyt?

Comment (mdelapenya) [reply cli/config/config.go:93]: Let's do it as you suggest

Comment (adam-stokes) [reply cli/config/config.go]: @mdelapenya Ok pushed a new commit, let me know what you think

File: cli/config/config.go [hunk 4]
```diff
@@ -94,9 +95,8 @@ func GetComposeFile(isProfile bool, composeName string) (string, error) {
 		"composeFilePath": composeFilePath,
 		"error":           err,
 		"type":            serviceType,
-	}).Trace("Compose file not found at workdir. Extracting from binary resources")
+	}).Tracef("Compose file not found at %s. Please make sure the file exists at the %s location", filepath.Dir(composeFilePath), composeFilePath)
```
Comment (mdelapenya) [inline cli/config/config.go:98]: Because the log fields already display the path:
```suggestion
	}).Trace("Compose file not found. Please make sure the file exists at the location")
```

File: cli/config/config.go (hunk 3 above)
Comment (mdelapenya) [reply cli/config/config.go]: Please take a look at #946 to be merged to this branch

**Review by mdelapenya — APPROVED** [review]

**Review by cachedout — APPROVED** [review]
