### PR TITLE
fix: read Git variables

### LINKED ISSUE #2739: Commit sha and repo is not passed to the build
I triggered this job on 8.3: https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/8.3/121/, where I explicitly passed the GITHUB_CHECK_SHA and GITHUB_CHECK_REPO variables (see parameters https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/8.3/121/parameters/)

The build did not passed those variables to the code, therefore the artifacts are not properly selected.

I verified it in 8.3. Will do the same for main now

### PR DESCRIPTION
**Pull request by mdelapenya**
- fix: pass Git variables in Jenkinsfile
- fix: laxy initialisation of the Git variables

## What does this PR do?
It passes the GITHUB_CHECK_SHA1 and GITHUB_CHECK_REPO variables to the Jenkinsfile, so that the Ansible code is able to pass them to the generated `.env` file in the remote machine.

This `.env` file is driving the execution, for that reason it's important it contains the right variables and values.

Besides that, we detected that the initialisation of those two variables was happening too early, before the `.env` was loaded (it was placed in the init() method, which has no deterministic order). Therefore, we are moving it to the initialisation of the default variables.

## Why is it important?
PRs from Beats, and eventually for the elastic-agent are not downloading the right artifacts, generated for the respective CIs when the packaging job of the repos happened.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests (`make unit-test`), and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Related issues

- Closes #2739

### CODE REVIEW

**Review by v1v — APPROVED** [review]
LGTM, though a minor comment regarding the default value for `elastic-agent`, even though it was already there.

What's the reason?

File: pkg/downloads/versions.go [hunk 1]
```diff
@@ -44,27 +44,19 @@ var GithubCommitSha1 string
 
 // GithubRepository represents the value of the "GITHUB_CHECK_REPO" environment variable
 // Default is "elastic-agent"
-var GithubRepository string
+var GithubRepository string = "elastic-agent"
```
Comment (mdelapenya) [inline pkg/downloads/versions.go:47]: @v1v we are setting this value as default because the tests are mainly focused on the agent scenarios. Those for beats are just a few including filebeat/metricbeat
