### PR TITLE
fix: pass platform version to metricbeat, not to the integration

### LINKED ISSUE #932: Beats PRs for maintenance branches are not adding platform for the metricbeat image
The metricbeat binary is properly downloaded for the PR, then it's tagged as `7.x-SNAPSHOT-amd64` but then it's pulled as `7.x-SNAPSHOT`, so the image is not present.

>[2021-03-24T14:11:46.470Z] time="2021-03-24T14:11:45Z" level=debug msg="Docker image loaded successfully" image="/tmp/commits%2F179917e2d3aa7263dd1e316b92ff87f83af4d38d%2Fmetricbeat%2Fmetricbeat-7.13.0-SNAPSHOT-linux-amd64.docker.tar.gz?generation=1616583087180001&alt=media881756650" response="{0xc000032180 true}
[2021-03-24T14:11:46.470Z] time="2021-03-24T14:11:45Z" level=debug msg="Docker image tagged successfully" src="docker.elastic.co/beats/metricbeat:7.13.0-SNAPSHOT" target="docker.elastic.co/observability-ci/metricbeat:7.x-SNAPSHOT-amd64"
[2021-03-24T14:11:49.770Z] {"level":"debug","time":"2021-03-24T14:11:49Z","message":"sent request with 0 transactions, 2 spans, 0 errors, 0 metricsets"}
[2021-03-24T14:11:52.313Z] {"level":"debug","time":"2021-03-24T14:11:51Z","message":"gathering metrics"}
[2021-03-24T14:12:02.319Z] {"level":"debug","time":"2021-03-24T14:12:01Z","message":"sent request with 0 transactions, 0 spans, 0 errors, 5 metricsets"}
[2021-03-24T14:12:24.286Z] {"level":"debug","time":"2021-03-24T14:12:21Z","message":"gathering metrics"}
[2021-03-24T14:12:32.425Z] {"level":"debug","time":"2021-03-24T14:12:31Z","message":"sent request with 0 transactions, 0 spans, 0 errors, 1 metricset"}
[2021-03-24T14:12:36.637Z] Found orphan containers (metricbeat_dropwizard_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[2021-03-24T14:12:36.637Z] Pulling metricbeat (docker.elastic.co/observability-ci/metricbeat:7.x-SNAPSHOT)...
[2021-03-24T14:12:36.637Z] manifest for docker.elastic.co/observability-ci/metricbeat:7.x-SNAPSHOT not found: manifest unknown: manifest unknown

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It passes the platform version (amd64/arm64) to the metricbeat service, not to the integration service

## Why is it important?
It was causing failures for Beats PRs, as they downloaded the metricbeat Docker image from a GCP bucket, then it was loaded into the Docker engine and tagged. Because of this bug, the image for the platform was not correctly tagged, causing the build to fail because the Docker image was not found.

It was not discovered on master because the functionality is covered by the `BEATS_USE_CI_SNAPSHOTS` or the `BEATS_LOCAL_PATH`, and only the first one is executed on CI, for PRs.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## How to test this PR locally

In master:
```shell
SUITE="metricbeat" TAGS="integrations && apache" GITHUB_CHECK_SHA1="179917e2d3aa7263dd1e316b92ff87f83af4d38d" BEATS_USE_CI_SNAPSHOTS=false TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```

For a PR in 7.x:
```shell
git checkout 7.x
echo "You need to cherrypick commits in this PR"
SUITE="metricbeat" TAGS="integrations && apache" GITHUB_CHECK_SHA1="179917e2d3aa7263dd1e316b92ff87f83af4d38d" BEATS_USE_CI_SNAPSHOTS=true TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```

## Related issues

- Caused by 6b9528b14d545c58680cd4d7d3711f2f14843b24 (#787)
- Closes #932

## Follow-ups
Backport to all maintenance branches

### CODE REVIEW

File: e2e/_suites/metricbeat/metricbeat_test.go [hunk 1]
```diff
@@ -406,10 +406,18 @@ func (mts *MetricbeatTestSuite) runMetricbeatService() error {
 			return err
 		}
 
+		mts.Version = mts.Version + "-amd64"
+
+		// wait for tagging to ensure the loaded image is present
+		e2e.Sleep(3 * time.Second)
```
Comment (mdelapenya) [inline e2e/_suites/metricbeat/metricbeat_test.go:412]: Otherwise, it could be the case that the process go faster that the docker engine to list the previously loaded image

File: e2e/_suites/metricbeat/metricbeat_test.go [hunk 2]
```diff
@@ -406,10 +406,18 @@ func (mts *MetricbeatTestSuite) runMetricbeatService() error {
...
+
 		err = docker.TagImage(
 			"docker.elastic.co/beats/metricbeat:"+metricbeatVersionBase,
-			"docker.elastic.co/observability-ci/metricbeat:"+mts.Version+"-amd64",
+			"docker.elastic.co/observability-ci/metricbeat:"+mts.Version,
 		)
+		if err != nil {
```
Comment (mdelapenya) [inline e2e/_suites/metricbeat/metricbeat_test.go:418]: This error was missing, so it's convenient to add it

File: e2e/_suites/metricbeat/metricbeat_test.go [hunk 3]
```diff
@@ -436,7 +444,7 @@ func (mts *MetricbeatTestSuite) runMetricbeatService() error {
 		"metricbeatConfigFile":  mts.configurationFile,
 		"metricbeatTag":         mts.Version,
 		"stackVersion":          stackVersion,
-		mts.ServiceName + "Tag": mts.ServiceVersion + "-amd64",
```
Comment (mdelapenya) [inline e2e/_suites/metricbeat/metricbeat_test.go:439]: I miserably added the tag to the wrong service 🤦‍♀️

File: e2e/_suites/metricbeat/metricbeat_test.go [hunk 4]
```diff
@@ -406,10 +406,18 @@ func (mts *MetricbeatTestSuite) runMetricbeatService() error {
 			return err
 		}
 
+		mts.Version = mts.Version + "-amd64"
```
Comment (mdelapenya) [inline e2e/_suites/metricbeat/metricbeat_test.go:409]: Updating the version only for this use case

File: e2e/_suites/metricbeat/metricbeat_test.go (hunk 1 above)
Comment (adam-stokes) [reply e2e/_suites/metricbeat/metricbeat_test.go:412]: Instead of adding a sleep could we just poll the docker api to verify the image is present? It may be useful to abstract some api's that could be reused in different areas and hopefully provide a better guarantee of making sure these requirements are met before proceeding. Thoughts?

Comment (mdelapenya) [reply e2e/_suites/metricbeat/metricbeat_test.go:412]: That would be lovely! Because this code (the tag image code) is very isolated and narrowed down to two usages, let's merge it as is and create an issue for that using the Docker client API.
