### PR TITLE
fix: retry tagging the loaded docker image up-to 15 seconds

### LINKED ISSUE #948: Tagging docker images after loading it fails inconsistently
https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/353/pipeline/223

I loaded the image 5 times, and the first tag failed.

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It applies a backoff strategy for tagging a docker image, removing the active wait of 3 seconds that was sitting in front of its usages. Now the tag will be retried up-to 15 seconds, which is enough.

## Why is it important?
We detected that 3 seconds is sometimes not enough on CI, causing flakiness in the test exeuction for Beats PRs.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the Unit tests for the CLI, and they are passing locally
- [x] I have run the End-2-End tests for the suite I'm working on, and they are passing locally
- [ ] I have noticed new Go dependencies (run `make notice` in the proper directory)

## Author's Checklist

- [ ]

## How to test this PR locally

```shell
git checkout 7.x
## echo 'Apply this PR to that branch as the commit relates to 7.x'
SUITE="metricbeat" TAGS="integrations && haproxy" GITHUB_CHECK_SHA1="7657100c68c502b0ab2e6cc934f18a527c95d9f4" BEATS_USE_CI_SNAPSHOTS=true TIMEOUT_FACTOR=3 LOG_LEVEL=TRACE DEVELOPER_MODE=true make -C e2e functional-test
```

## Related issues

- Fixes #948
- Workaround until #942 is in place

## Follow-ups
See #942

### CODE REVIEW

File: cli/docker/docker.go [hunk 1]
```diff
@@ -211,21 +213,48 @@ func LoadImage(imagePath string) error {
...
+
+		err := dockerClient.ImageTag(context.Background(), src, target)
+		if err != nil {
+			log.WithFields(log.Fields{
+				"error":       err,
+				"src":         src,
+				"target":      target,
+				"elapsedTime": exp.GetElapsedTime(),
+				"retries":     retryCount,
+			}).Error("Could not tag the Docker image.")
```
Comment (mdelapenya) [inline cli/docker/docker.go:244]:
```suggestion
			}).Warn("Could not tag the Docker image.")
```

**Review by cachedout — APPROVED** [review]

**Comment by mdelapenya** [comment]
@adam-stokes I'm going to merge this as it's affecting Beats PRs. We can change this new method in #942
